### ISSUE TITLE
How to change deselected days text color without changing the selected ones highligh color?

### ISSUE THREAD

**Issue by bzsolt0402** [DavidProdinger/Weekdays-Selector#5]
It seems like highligh color changes both the color of the selected days and the text of the unselected ones. My problem is that I would like to change the deselected text color to grey while keeping the highlight orange in my case. Is there a solution for this?
Thank you in advance!

**Comment by DavidProdinger** [comment]
Thank you for submitting your unsupported use-case.
Fixed in #6
