### ISSUE TITLE
Select All Days!

### ISSUE THREAD

**Issue by brittle123** [DavidProdinger/Weekdays-Selector#9]
Hello @DavidProdinger !
I want to select all days on tapping toggle button which select and deselect all days. Please do tell me how to do it ASAP!
Thanks & Regards.

**Comment by Falke-Design** [comment]
Read the Readme then you will have your answer ASAP ...

```
List<Integer> days = Arrays.asList(Calendar.MONDAY, Calendar.WEDNESDAY, Calendar.FRIDAY, Calendar.SUNDAY);
widget.setSelectedDays(days);
```
